branch-defaults:
  master:
    environment: prod-tsukaby-common
global:
  application_name: tsukaby-common
  default_ec2_keyname: aws
  default_platform: Multi-container Docker 1.6.0 (Generic)
  default_region: ap-northeast-1
  profile: null
  sc: git
