ApplicationName: tsukaby-common
DateUpdated: 2015-05-09 08:27:57+00:00
EnvironmentName: prod-tsukaby-common
SolutionStackName: 64bit Amazon Linux 2015.03 v1.4.0 running Multi-container Docker
  1.6.0 (Generic)
settings:
  AWSEBAutoScalingScaleDownPolicy.aws:autoscaling:trigger:
    LowerBreachScaleIncrement: '-1'
  AWSEBAutoScalingScaleUpPolicy.aws:autoscaling:trigger:
    UpperBreachScaleIncrement: '1'
  AWSEBCloudwatchAlarmHigh.aws:autoscaling:trigger:
    UpperThreshold: '6000000'
  AWSEBCloudwatchAlarmLow.aws:autoscaling:trigger:
    BreachDuration: '5'
    EvaluationPeriods: '1'
    LowerThreshold: '2000000'
    MeasureName: NetworkOut
    Period: '5'
    Statistic: Average
    Unit: Bytes
  aws:autoscaling:asg:
    Availability Zones: Any
    Cooldown: '360'
    Custom Availability Zones: null
    MaxSize: '4'
    MinSize: '1'
  aws:autoscaling:launchconfiguration:
    BlockDeviceMappings: null
    EC2KeyName: aws
    IamInstanceProfile: aws-elasticbeanstalk-ec2-role
    ImageId: ami-8ab27d8a
    InstanceType: t1.micro
    MonitoringInterval: 5 minute
    RootVolumeIOPS: null
    RootVolumeSize: null
    RootVolumeType: null
    SSHSourceRestriction: tcp,22,22,0.0.0.0/0
    SecurityGroups: awseb-e-pfehaebmvm-stack-AWSEBSecurityGroup-U3WL6S5U6BIP
  aws:autoscaling:updatepolicy:rollingupdate:
    MaxBatchSize: '1'
    MinInstancesInService: '1'
    PauseTime: null
    RollingUpdateEnabled: 'true'
    RollingUpdateType: Health
    Timeout: PT30M
  aws:ec2:vpc:
    AssociatePublicIpAddress: null
    ELBScheme: public
    ELBSubnets: null
    Subnets: null
    VPCId: null
  aws:elasticbeanstalk:application:
    Application Healthcheck URL: null
  aws:elasticbeanstalk:command:
    BatchSize: '30'
    BatchSizeType: Percentage
    Timeout: '600'
  aws:elasticbeanstalk:control:
    DefaultSSHPort: '22'
    LaunchTimeout: '0'
    LaunchType: Migration
    RollbackLaunchOnFailure: 'false'
  aws:elasticbeanstalk:environment:
    EnvironmentType: LoadBalanced
  aws:elasticbeanstalk:hostmanager:
    LogPublicationControl: 'false'
  aws:elasticbeanstalk:monitoring:
    Automatically Terminate Unhealthy Instances: 'true'
  aws:elasticbeanstalk:sns:topics:
    Notification Endpoint: null
    Notification Protocol: email
    Notification Topic ARN: null
    Notification Topic Name: null
  aws:elb:healthcheck:
    HealthyThreshold: '3'
    Interval: '30'
    Target: TCP:80
    Timeout: '5'
    UnhealthyThreshold: '5'
  aws:elb:listener:80:
    InstancePort: '80'
    InstanceProtocol: HTTP
    ListenerEnabled: 'true'
    ListenerProtocol: HTTP
    PolicyNames: null
    SSLCertificateId: null
  aws:elb:loadbalancer:
    CrossZone: 'true'
    LoadBalancerHTTPPort: '80'
    LoadBalancerHTTPSPort: 'OFF'
    LoadBalancerPortProtocol: HTTP
    LoadBalancerSSLPortProtocol: HTTPS
    SSLCertificateId: null
  aws:elb:policies:
    ConnectionDrainingEnabled: 'true'
    ConnectionDrainingTimeout: '20'
    ConnectionSettingIdleTimeout: '60'
    Stickiness Cookie Expiration: '0'
    Stickiness Policy: 'false'
